version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/static:/code/static
      - ./backend/media:/code/media
      - ./backend/staticfiles:/code/staticfiles
      - ./backend/logs:/code/logs
      - ./backend/django_cache:/code/django_cache
      - ./backend/db.sqlite3:/code/db.sqlite3
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-w@p+fa&&omp^oa7&n68==+0@4^+lert43yw8v8yjhrxip821po
      - ALLOWED_HOSTS=localhost,127.0.0.1,159.69.87.39,nasbfix.ir,171.22.27.104
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./backend/staticfiles:/static
      - ./backend/media:/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web

volumes:
  postgres_data:
    name: ac_service_postgres_data
    driver: local

